apiVersion: v1
kind: Application
metadata:
  name: myapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sowmya2373/aws-app-config.git
    targetRevision: HEAD\
    path: dev
  destination: 
    server: http://127.0.0.1:44477/api/v1/namespaces/kubernetes-dashboard/services/http:kubernetes-dashboard:/proxy/
    namespace: myapp
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
